const CoursesData = [
  {
    id: 1,
    title: 'آموزش معاملات آپشن بیت کوین',
    category: 'دوره های رایگان',
    price: 0,
    img: './images/course-photo-1.jpeg',
    desc: `جواد آذری`,
  },
  {
    id: 2,
    title: 'آموزش ارزهای دیجیتال بازار کریپتو',
    category: 'محبوب ترین دوره',
    price: 1300000,
    img: './images/course-photo-2.jpeg',
    desc: `سید علی هاشمی`,
  },
  {
    id: 3,
    title: 'آموزش تشخیص نهنگ های بیت کوین',
    category: 'دوره های رایگان',
    price: 0,
    img: './images/course-photo-3.jpeg',
    desc: `علی جهرمی`,
  },
  {
    id: 4,
    title: 'آموزش نحوه خرید و فروش بیت کوین',
    category: 'پرفروش ترین دوره',
    price: 2000000,
    img: './images/course-photo-4.jpeg',
    desc: `علی اکبری`,
  },
  {
    id: 5,
    title: 'آموزش مدیریت مدل UTXO بیت کوین',
    category: 'محبوب ترین دوره',
    price: 2200000,
    img: './images/course-photo-5.jpeg',
    desc: `مجید جواهری`,
  },
  {
    id: 6,
    title: 'آموزش مقدماتی معرفی آلت کوین ها',
    category: 'دوره های رایگان',
    price: 0,
    img: './images/course-photo-7.jpeg',
    desc: `ساسان درویشی`,
  },
  {
    id: 7,
    title: 'تفاوت بین نودها بیت کوین و ماینرها',
    category: 'پرفروش ترین دوره',
    price: 800000,
    img: './images/course-photo-6.jpeg',
    desc: `حسین مهرجو`,
  },
  {
    id: 8,
    title: 'آموزش تحلیل و معاملات بازارهای مالی',
    category: 'محبوب ترین دوره',
    price: 1200000,
    img: './images/course-photo-8.jpeg',
    desc: `صادق موسوی`,
  },
];

export default CoursesData;
