import type { Metadata } from "next";
import { ThemeProvider } from '@/app/components/context/ThemeContext'
import ScrollToTop from '@/app/components/ScrollToTop'
import Layout from '@/app/components/Layout/Layout'
import "./globals.css";
import 'flowbite';



export const metadata: Metadata = {
  title: "آکادمی ارزهای دیجیتال",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <ScrollToTop />
          <Layout>
            {children}
          </Layout>
        </ThemeProvider>
      </body>
    </html>
  );
}
